sets.exported={
    main="Odium",
    sub={ name="Atoyac", augments={'Accuracy+30','Evasion+15',}},
    range={ name="Doomsday", augments={'Rng.Atk.+19','"Snapshot"+2','AGI+19',}},
    ammo="Orichalc. Bullet",
    head="Meghanada Visor +1",
    body={ name="Rawhide Vest", augments={'HP+46','Accuracy+13','Evasion+18',}},
    hands="Meg. Gloves +1",
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Crit.hit rate+1','"Mag.Atk.Bns."+15',}},
    feet={ name="Herculean Boots", augments={'Accuracy+25','"Triple Atk."+2','Attack+15',}},
    neck="Sanctity Necklace",
    waist="Eschan Stone",
    left_ear="Novio Earring",
    right_ear="Friomisi Earring",
    left_ring="Archon Ring",
    right_ring="Adoulin Ring",
    back={ name="Gunslinger's Cape", augments={'Enmity-3','"Mag.Atk.Bns."+2','"Phantom Roll" ability delay -2',}},
}