sets.exported={
    main="Burtgang",
    sub="Ochain",
    ammo="Staunch Tathlum +1",
    head={ name="Carmine Mask +1", augments={'Accuracy+20','Mag. Acc.+12','"Fast Cast"+4',}},
    body="Chozor. Coselete",
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs={ name="Odyssean Cuisses", augments={'"Fast Cast"+5','Mag. Acc.+7','"Mag.Atk.Bns."+7',}},
    feet="Odyssean Greaves",
    neck="Baetyl Pendant",
    waist="Fucho-no-Obi",
    left_ear="Loquac. Earring",
    right_ear="Enchntr. Earring +1",
    left_ring="Defending Ring",
    right_ring="Kishar Ring",
    back={ name="Rudianos's Mantle", augments={'"Fast Cast"+10',}},
}