sets.exported={
    main="Fettering Blade",
    sub="Odium",
    range="Fomalhaut",
    ammo="Chrono Bullet",
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body="Laksa. Frac +2",
    hands="Meg. Gloves +2",
    legs="Meg. Chausses +2",
    feet="Meg. Jam. +2",
    neck="Sanctity Necklace",
    waist="Eschan Stone",
    left_ear="Infused Earring",
    right_ear="Ishvara Earring",
    left_ring="Regal Ring",
    right_ring="Dingir Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+5','"Store TP"+10',}},
}