sets.exported={
    main="Heishi Shorinken",
    sub={ name="Kanaria", augments={'"Triple Atk."+2','AGI+3','Attack+7','DMG:+11',}},
    ammo="Yamarang",
    head={ name="Adhemar Bonnet +1", augments={'STR+12','DEX+12','Attack+20',}},
    body={ name="Adhemar Jacket +1", augments={'STR+12','DEX+12','Attack+20',}},
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    legs={ name="Ryuo Hakama +1", augments={'Accuracy+25','"Store TP"+5','Phys. dmg. taken -4',}},
    feet={ name="Herculean Boots", augments={'Accuracy+14 Attack+14','"Triple Atk."+3','Accuracy+15',}},
    neck="Moonbeam Nodowa",
    waist="Reiki Yotai",
    left_ear="Telos Earring",
    right_ear="Brutal Earring",
    left_ring="Chirich Ring +1",
    right_ring="Epona's Ring",
    back={ name="Yokaze Mantle", augments={'STR+2','DEX+2','Sklchn.dmg.+3%',}},
}