sets.exported={
    main={ name="Kali", augments={'Mag. Acc.+15','String instrument skill +10','Wind instrument skill +10',}},
    sub="Kali",
    range="Daurdabla",
    head="Aya. Zucchetto +2",
    body="Inyanga Jubbah +2",
    hands="Inyan. Dastanas +2",
    legs="Aya. Cosciales +2",
    feet="Aya. Gambieras +2",
    neck="Moonbow Whistle",
    waist="Eschan Stone",
    left_ear="Digni. Earring",
    right_ear="Loquac. Earring",
    left_ring="Kishar Ring",
    right_ring="Inyanga Ring",
    back="Aurist's Cape +1",
}