sets.exported={
    main="Perun +1",
    sub="Nusku Shield",
    range={ name="Doomsday", augments={'Rng.Atk.+19','"Snapshot"+2','AGI+19',}},
    ammo="Decimating Bullet",
    head="Meghanada Visor +2",
    body="Meg. Cuirie +2",
    hands="Meg. Gloves +2",
    legs="Meg. Chausses +1",
    feet="Meg. Jam. +2",
    neck="Gaudryi Necklace",
    waist="Eschan Stone",
    left_ear="Telos Earring",
    right_ear="Enervating Earring",
    left_ring="Cacoethic Ring +1",
    right_ring="Haverton Ring",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10',}},
}