sets.exported={
    main="Kali",
    sub="Genbu's Shield",
    range="Daurdabla",
    head="Inyanga Tiara +1",
    body="Inyanga Jubbah +2",
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs="Assid. Pants +1",
    feet="Brioso Slippers +2",
    neck="Bathy Choker +1",
    waist="Fucho-no-Obi",
    left_ear="Infused Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Warp Ring",
    right_ring="Inyanga Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+49%','VIT+2','"Mag.Atk.Bns."+2','DEF+8',}},
}