sets.exported={
    main="Aeneas",
    sub={ name="Taming Sari", augments={'STR+9','DEX+8','DMG:+14',}},
    ammo="Yamarang",
    head="Meghanada Visor +2",
    body="Meg. Cuirie +2",
    hands="Meg. Gloves +2",
    legs="Meg. Chausses +1",
    feet={ name="Herculean Boots", augments={'Accuracy+14 Attack+14','"Triple Atk."+3','Accuracy+15',}},
    neck="Bathy Choker +1",
    waist="Gishdubar Sash",
    left_ear="Odnowa Earring +1",
    right_ear="Odnowa Earring",
    left_ring="Defending Ring",
    right_ring={ name="Dark Ring", augments={'Phys. dmg. taken -5%','Magic dmg. taken -4%','Breath dmg. taken -3%',}},
    back="Solemnity Cape",
}